[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bestlib"
version = "0.1.0"
description = "MatrixLayout widget for dashboards with D3.js"
authors = [
    { name="Nahia, Alejandro, Max" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ipython>=8",
    "jupyterlab>=4",
    "ipywidgets>=8",
    "pandas>=1.3.0",
    "numpy>=1.20.0",
]

[tool.setuptools]
packages = ["BESTLIB"]
include-package-data = true

[tool.setuptools.package-data]
BESTLIB = ["*.js", "*.css"]
